package entidades;
// Generated 16/12/2020 15:28:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private Set<UsuarioAdmin> usuarioAdmins = new HashSet<UsuarioAdmin>(0);

    public Area() {
    }

	
    public Area(String nombre) {
        this.nombre = nombre;
    }
    public Area(String nombre, Set<UsuarioAdmin> usuarioAdmins) {
       this.nombre = nombre;
       this.usuarioAdmins = usuarioAdmins;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<UsuarioAdmin> getUsuarioAdmins() {
        return this.usuarioAdmins;
    }
    
    public void setUsuarioAdmins(Set<UsuarioAdmin> usuarioAdmins) {
        this.usuarioAdmins = usuarioAdmins;
    }




}


