package entidades;
// Generated 21/07/2020 15:25:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CarniceriaLocal generated by hbm2java
 */
public class CarniceriaLocal  implements java.io.Serializable {


     private Integer id;
     private CarniceriaEmpresa carniceriaEmpresa;
     private Localidad localidad;
     private Provincia provincia;
     private String nombre;
     private String responsable;
     private String direccion;
     private String telefono;
     private String email;
     private Character estado;
     private Set<MovInventario> movInventarios = new HashSet<MovInventario>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public CarniceriaLocal() {
    }

	
    public CarniceriaLocal(CarniceriaEmpresa carniceriaEmpresa) {
        this.carniceriaEmpresa = carniceriaEmpresa;
    }
    public CarniceriaLocal(CarniceriaEmpresa carniceriaEmpresa, Localidad localidad, Provincia provincia, String nombre, String responsable, String direccion, String telefono, String email, Character estado, Set<MovInventario> movInventarios, Set<Venta> ventas) {
       this.carniceriaEmpresa = carniceriaEmpresa;
       this.localidad = localidad;
       this.provincia = provincia;
       this.nombre = nombre;
       this.responsable = responsable;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.estado = estado;
       this.movInventarios = movInventarios;
       this.ventas = ventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CarniceriaEmpresa getCarniceriaEmpresa() {
        return this.carniceriaEmpresa;
    }
    
    public void setCarniceriaEmpresa(CarniceriaEmpresa carniceriaEmpresa) {
        this.carniceriaEmpresa = carniceriaEmpresa;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set<MovInventario> getMovInventarios() {
        return this.movInventarios;
    }
    
    public void setMovInventarios(Set<MovInventario> movInventarios) {
        this.movInventarios = movInventarios;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


