package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ComandaDetalle generated by hbm2java
 */
public class ComandaDetalle  implements java.io.Serializable {


     private Integer id;
     private Comanda comanda;
     private Producto producto;
     private UnidadMedida unidadMedida;
     private BigDecimal cantidad;
     private String observaciones;

    public ComandaDetalle() {
    }

	
    public ComandaDetalle(Comanda comanda, Producto producto, UnidadMedida unidadMedida, BigDecimal cantidad) {
        this.comanda = comanda;
        this.producto = producto;
        this.unidadMedida = unidadMedida;
        this.cantidad = cantidad;
    }
    public ComandaDetalle(Comanda comanda, Producto producto, UnidadMedida unidadMedida, BigDecimal cantidad, String observaciones) {
       this.comanda = comanda;
       this.producto = producto;
       this.unidadMedida = unidadMedida;
       this.cantidad = cantidad;
       this.observaciones = observaciones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Comanda getComanda() {
        return this.comanda;
    }
    
    public void setComanda(Comanda comanda) {
        this.comanda = comanda;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


