package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comanda generated by hbm2java
 */
public class Comanda  implements java.io.Serializable {


     private Integer id;
     private Mesa mesa;
     private Mozo mozo;
     private Date fecha;
     private String observaciones;
     private char estado;
     private Set<ComandaDetalle> comandaDetalles = new HashSet<ComandaDetalle>(0);

    public Comanda() {
    }

	
    public Comanda(Mesa mesa, Mozo mozo, Date fecha, char estado) {
        this.mesa = mesa;
        this.mozo = mozo;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Comanda(Mesa mesa, Mozo mozo, Date fecha, String observaciones, char estado, Set<ComandaDetalle> comandaDetalles) {
       this.mesa = mesa;
       this.mozo = mozo;
       this.fecha = fecha;
       this.observaciones = observaciones;
       this.estado = estado;
       this.comandaDetalles = comandaDetalles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Mozo getMozo() {
        return this.mozo;
    }
    
    public void setMozo(Mozo mozo) {
        this.mozo = mozo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<ComandaDetalle> getComandaDetalles() {
        return this.comandaDetalles;
    }
    
    public void setComandaDetalles(Set<ComandaDetalle> comandaDetalles) {
        this.comandaDetalles = comandaDetalles;
    }




}


