package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CondIva generated by hbm2java
 */
public class CondIva  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Productor> productors = new HashSet<Productor>(0);
     private Set<Comisionista> comisionistas = new HashSet<Comisionista>(0);

    public CondIva() {
    }

	
    public CondIva(String nombre) {
        this.nombre = nombre;
    }
    public CondIva(String nombre, Set<Cliente> clientes, Set<Productor> productors, Set<Comisionista> comisionistas) {
       this.nombre = nombre;
       this.clientes = clientes;
       this.productors = productors;
       this.comisionistas = comisionistas;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Productor> getProductors() {
        return this.productors;
    }
    
    public void setProductors(Set<Productor> productors) {
        this.productors = productors;
    }
    public Set<Comisionista> getComisionistas() {
        return this.comisionistas;
    }
    
    public void setComisionistas(Set<Comisionista> comisionistas) {
        this.comisionistas = comisionistas;
    }




}


