package entidades;
// Generated 16/12/2020 15:28:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fletero generated by hbm2java
 */
public class Fletero  implements java.io.Serializable {


     private Short id;
     private Tipoid tipoid= new Tipoid();
     private UsuarioAdmin usuarioAdmin= new UsuarioAdmin();
     private String numId;
     private String nombre;
     private char estado;
     private Set<EfectivoFlete> efectivoFletes = new HashSet<EfectivoFlete>(0);
     private Set<Viaje> viajes = new HashSet<Viaje>(0);
     private Set<LiquidacionFlete> liquidacionFletes = new HashSet<LiquidacionFlete>(0);

    public Fletero() {
    }

	
    public Fletero(String nombre, char estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Fletero(Tipoid tipoid, UsuarioAdmin usuarioAdmin, String numId, String nombre, char estado, Set<EfectivoFlete> efectivoFletes, Set<Viaje> viajes, Set<LiquidacionFlete> liquidacionFletes) {
       this.tipoid = tipoid;
       this.usuarioAdmin = usuarioAdmin;
       this.numId = numId;
       this.nombre = nombre;
       this.estado = estado;
       this.efectivoFletes = efectivoFletes;
       this.viajes = viajes;
       this.liquidacionFletes = liquidacionFletes;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public Tipoid getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(Tipoid tipoid) {
        this.tipoid = tipoid;
    }
    public UsuarioAdmin getUsuarioAdmin() {
        return this.usuarioAdmin;
    }
    
    public void setUsuarioAdmin(UsuarioAdmin usuarioAdmin) {
        this.usuarioAdmin = usuarioAdmin;
    }
    public String getNumId() {
        return this.numId;
    }
    
    public void setNumId(String numId) {
        this.numId = numId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<EfectivoFlete> getEfectivoFletes() {
        return this.efectivoFletes;
    }
    
    public void setEfectivoFletes(Set<EfectivoFlete> efectivoFletes) {
        this.efectivoFletes = efectivoFletes;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }
    public Set<LiquidacionFlete> getLiquidacionFletes() {
        return this.liquidacionFletes;
    }
    
    public void setLiquidacionFletes(Set<LiquidacionFlete> liquidacionFletes) {
        this.liquidacionFletes = liquidacionFletes;
    }




}


