package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MesaComprobante generated by hbm2java
 */
public class MesaComprobante  implements java.io.Serializable {


     private Integer id;
     private FormaPago formaPago;
     private Mesa mesa;
     private Tarjeta tarjeta;
     private TipoFactura tipoFactura;
     private char tipoComprobante;
     private BigDecimal valor;

    public MesaComprobante() {
    }

	
    public MesaComprobante(FormaPago formaPago, Mesa mesa, char tipoComprobante, BigDecimal valor) {
        this.formaPago = formaPago;
        this.mesa = mesa;
        this.tipoComprobante = tipoComprobante;
        this.valor = valor;
    }
    public MesaComprobante(FormaPago formaPago, Mesa mesa, Tarjeta tarjeta, TipoFactura tipoFactura, char tipoComprobante, BigDecimal valor) {
       this.formaPago = formaPago;
       this.mesa = mesa;
       this.tarjeta = tarjeta;
       this.tipoFactura = tipoFactura;
       this.tipoComprobante = tipoComprobante;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public TipoFactura getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(TipoFactura tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public char getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(char tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


