package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1



/**
 * MesaActual generated by hbm2java
 */
public class MesaActual  implements java.io.Serializable {


     private Integer id;
     private Mesa mesa;
     private MesaNumero mesaNumero;

    public MesaActual() {
    }

    public MesaActual(Mesa mesa, MesaNumero mesaNumero) {
       this.mesa = mesa;
       this.mesaNumero = mesaNumero;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public MesaNumero getMesaNumero() {
        return this.mesaNumero;
    }
    
    public void setMesaNumero(MesaNumero mesaNumero) {
        this.mesaNumero = mesaNumero;
    }




}


