package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MesaDetAdicional generated by hbm2java
 */
public class MesaDetAdicional  implements java.io.Serializable {


     private Integer id;
     private Adicional adicional;
     private MesaDet mesaDet;
     private BigDecimal valor;

    public MesaDetAdicional() {
    }

    public MesaDetAdicional(Adicional adicional, MesaDet mesaDet, BigDecimal valor) {
       this.adicional = adicional;
       this.mesaDet = mesaDet;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Adicional getAdicional() {
        return this.adicional;
    }
    
    public void setAdicional(Adicional adicional) {
        this.adicional = adicional;
    }
    public MesaDet getMesaDet() {
        return this.mesaDet;
    }
    
    public void setMesaDet(MesaDet mesaDet) {
        this.mesaDet = mesaDet;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


