package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1



/**
 * MesaDetPreferencia generated by hbm2java
 */
public class MesaDetPreferencia  implements java.io.Serializable {


     private Integer id;
     private MesaDet mesaDet;
     private Preferencia preferencia;

    public MesaDetPreferencia() {
    }

    public MesaDetPreferencia(MesaDet mesaDet, Preferencia preferencia) {
       this.mesaDet = mesaDet;
       this.preferencia = preferencia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MesaDet getMesaDet() {
        return this.mesaDet;
    }
    
    public void setMesaDet(MesaDet mesaDet) {
        this.mesaDet = mesaDet;
    }
    public Preferencia getPreferencia() {
        return this.preferencia;
    }
    
    public void setPreferencia(Preferencia preferencia) {
        this.preferencia = preferencia;
    }




}


