package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MesaDet generated by hbm2java
 */
public class MesaDet  implements java.io.Serializable {


     private Integer id;
     private Mesa mesa;
     private Preferencia preferencia;
     private Producto producto;
     private UnidadMedida unidadMedida;
     private Integer idTipoComida;
     private char integraCombo;
     private String observacion;
     private BigDecimal cantidad;
     private BigDecimal precioUnitario;
     private BigDecimal valorAdicional;
     private BigDecimal precioTotal;
     private char estado;
     private int idComanda;
     private Date horaPedido;
     private Date horaEnvio;
     private Set<MesaDetAdicional> mesaDetAdicionals = new HashSet<MesaDetAdicional>(0);
     private Set<MesaDetPreferencia> mesaDetPreferencias = new HashSet<MesaDetPreferencia>(0);

    public MesaDet() {
    }

	
    public MesaDet(Mesa mesa, Producto producto, UnidadMedida unidadMedida, char integraCombo, BigDecimal cantidad, BigDecimal precioUnitario, BigDecimal valorAdicional, BigDecimal precioTotal, char estado, int idComanda, Date horaPedido) {
        this.mesa = mesa;
        this.producto = producto;
        this.unidadMedida = unidadMedida;
        this.integraCombo = integraCombo;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.valorAdicional = valorAdicional;
        this.precioTotal = precioTotal;
        this.estado = estado;
        this.idComanda = idComanda;
        this.horaPedido = horaPedido;
    }
    public MesaDet(Mesa mesa, Preferencia preferencia, Producto producto, UnidadMedida unidadMedida, Integer idTipoComida, char integraCombo, String observacion, BigDecimal cantidad, BigDecimal precioUnitario, BigDecimal valorAdicional, BigDecimal precioTotal, char estado, int idComanda, Date horaPedido, Date horaEnvio, Set<MesaDetAdicional> mesaDetAdicionals, Set<MesaDetPreferencia> mesaDetPreferencias) {
       this.mesa = mesa;
       this.preferencia = preferencia;
       this.producto = producto;
       this.unidadMedida = unidadMedida;
       this.idTipoComida = idTipoComida;
       this.integraCombo = integraCombo;
       this.observacion = observacion;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.valorAdicional = valorAdicional;
       this.precioTotal = precioTotal;
       this.estado = estado;
       this.idComanda = idComanda;
       this.horaPedido = horaPedido;
       this.horaEnvio = horaEnvio;
       this.mesaDetAdicionals = mesaDetAdicionals;
       this.mesaDetPreferencias = mesaDetPreferencias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Preferencia getPreferencia() {
        return this.preferencia;
    }
    
    public void setPreferencia(Preferencia preferencia) {
        this.preferencia = preferencia;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public Integer getIdTipoComida() {
        return this.idTipoComida;
    }
    
    public void setIdTipoComida(Integer idTipoComida) {
        this.idTipoComida = idTipoComida;
    }
    public char getIntegraCombo() {
        return this.integraCombo;
    }
    
    public void setIntegraCombo(char integraCombo) {
        this.integraCombo = integraCombo;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public BigDecimal getValorAdicional() {
        return this.valorAdicional;
    }
    
    public void setValorAdicional(BigDecimal valorAdicional) {
        this.valorAdicional = valorAdicional;
    }
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public int getIdComanda() {
        return this.idComanda;
    }
    
    public void setIdComanda(int idComanda) {
        this.idComanda = idComanda;
    }
    public Date getHoraPedido() {
        return this.horaPedido;
    }
    
    public void setHoraPedido(Date horaPedido) {
        this.horaPedido = horaPedido;
    }
    public Date getHoraEnvio() {
        return this.horaEnvio;
    }
    
    public void setHoraEnvio(Date horaEnvio) {
        this.horaEnvio = horaEnvio;
    }
    public Set<MesaDetAdicional> getMesaDetAdicionals() {
        return this.mesaDetAdicionals;
    }
    
    public void setMesaDetAdicionals(Set<MesaDetAdicional> mesaDetAdicionals) {
        this.mesaDetAdicionals = mesaDetAdicionals;
    }
    public Set<MesaDetPreferencia> getMesaDetPreferencias() {
        return this.mesaDetPreferencias;
    }
    
    public void setMesaDetPreferencias(Set<MesaDetPreferencia> mesaDetPreferencias) {
        this.mesaDetPreferencias = mesaDetPreferencias;
    }




}


