package entidades;
// Generated 16/12/2020 15:28:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MovInventarioDet generated by hbm2java
 */
public class MovInventarioDet  implements java.io.Serializable {


     private Integer id;
     private MovInventario movInventario;
     private int idGarron;
     private char tipo;
     private BigDecimal cantidad;

    public MovInventarioDet() {
    }

    public MovInventarioDet(MovInventario movInventario, int idGarron, char tipo, BigDecimal cantidad) {
       this.movInventario = movInventario;
       this.idGarron = idGarron;
       this.tipo = tipo;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MovInventario getMovInventario() {
        return this.movInventario;
    }
    
    public void setMovInventario(MovInventario movInventario) {
        this.movInventario = movInventario;
    }
    public int getIdGarron() {
        return this.idGarron;
    }
    
    public void setIdGarron(int idGarron) {
        this.idGarron = idGarron;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


