package entidades;
// Generated 16/12/2020 15:28:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovInventario generated by hbm2java
 */
public class MovInventario  implements java.io.Serializable {


     private Integer id;
     private LocalCarniceria localCarniceria;
     private UsuarioAdmin usuarioAdmin;
     private char tipoMov;
     private Date fecMov;
     private String observaciones;
     private Set<MovInventarioDet> movInventarioDets = new HashSet<MovInventarioDet>(0);

    public MovInventario() {
    }

	
    public MovInventario(LocalCarniceria localCarniceria, UsuarioAdmin usuarioAdmin, char tipoMov, Date fecMov) {
        this.localCarniceria = localCarniceria;
        this.usuarioAdmin = usuarioAdmin;
        this.tipoMov = tipoMov;
        this.fecMov = fecMov;
    }
    public MovInventario(LocalCarniceria localCarniceria, UsuarioAdmin usuarioAdmin, char tipoMov, Date fecMov, String observaciones, Set<MovInventarioDet> movInventarioDets) {
       this.localCarniceria = localCarniceria;
       this.usuarioAdmin = usuarioAdmin;
       this.tipoMov = tipoMov;
       this.fecMov = fecMov;
       this.observaciones = observaciones;
       this.movInventarioDets = movInventarioDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public UsuarioAdmin getUsuarioAdmin() {
        return this.usuarioAdmin;
    }
    
    public void setUsuarioAdmin(UsuarioAdmin usuarioAdmin) {
        this.usuarioAdmin = usuarioAdmin;
    }
    public char getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(char tipoMov) {
        this.tipoMov = tipoMov;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<MovInventarioDet> getMovInventarioDets() {
        return this.movInventarioDets;
    }
    
    public void setMovInventarioDets(Set<MovInventarioDet> movInventarioDets) {
        this.movInventarioDets = movInventarioDets;
    }




}


