package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mozo generated by hbm2java
 */
public class Mozo  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private Localidad localidad;
     private Provincia provincia;
     private Integer idUsuario;
     private String apellido;
     private String nombre;
     private String nombrePila;
     private String numeroDni;
     private Date fecNac;
     private String direccion;
     private String observaciones;
     private Set<Mesa> mesas = new HashSet<Mesa>(0);
     private Set<Comanda> comandas = new HashSet<Comanda>(0);

    public Mozo() {
    }

	
    public Mozo(Empresa empresa, String apellido, String nombre, String nombrePila) {
        this.empresa = empresa;
        this.apellido = apellido;
        this.nombre = nombre;
        this.nombrePila = nombrePila;
    }
    public Mozo(Empresa empresa, Localidad localidad, Provincia provincia, Integer idUsuario, String apellido, String nombre, String nombrePila, String numeroDni, Date fecNac, String direccion, String observaciones, Set<Mesa> mesas, Set<Comanda> comandas) {
       this.empresa = empresa;
       this.localidad = localidad;
       this.provincia = provincia;
       this.idUsuario = idUsuario;
       this.apellido = apellido;
       this.nombre = nombre;
       this.nombrePila = nombrePila;
       this.numeroDni = numeroDni;
       this.fecNac = fecNac;
       this.direccion = direccion;
       this.observaciones = observaciones;
       this.mesas = mesas;
       this.comandas = comandas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombrePila() {
        return this.nombrePila;
    }
    
    public void setNombrePila(String nombrePila) {
        this.nombrePila = nombrePila;
    }
    public String getNumeroDni() {
        return this.numeroDni;
    }
    
    public void setNumeroDni(String numeroDni) {
        this.numeroDni = numeroDni;
    }
    public Date getFecNac() {
        return this.fecNac;
    }
    
    public void setFecNac(Date fecNac) {
        this.fecNac = fecNac;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<Mesa> getMesas() {
        return this.mesas;
    }
    
    public void setMesas(Set<Mesa> mesas) {
        this.mesas = mesas;
    }
    public Set<Comanda> getComandas() {
        return this.comandas;
    }
    
    public void setComandas(Set<Comanda> comandas) {
        this.comandas = comandas;
    }




}


