package entidades;
// Generated 21 ene. 2022 15:27:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductoPrecio generated by hbm2java
 */
public class ProductoPrecio  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private Date fecIni;
     private Date fecFin;
     private BigDecimal precio;

    public ProductoPrecio() {
    }

    public ProductoPrecio(Producto producto, Date fecIni, Date fecFin, BigDecimal precio) {
       this.producto = producto;
       this.fecIni = fecIni;
       this.fecFin = fecFin;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFecIni() {
        return this.fecIni;
    }
    
    public void setFecIni(Date fecIni) {
        this.fecIni = fecIni;
    }
    public Date getFecFin() {
        return this.fecFin;
    }
    
    public void setFecFin(Date fecFin) {
        this.fecFin = fecFin;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


