package entidades;
// Generated 4 abr. 2022 15:58:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Rubro rubro= new Rubro();
     private Unidad unidad= new Unidad();
     private String codigo;
     private String nombre;
     private String descripcion;
     private char tipo;
     private BigDecimal porcIva;
     private BigDecimal stockMinimo;
     private char estado;
     private Set<RemitoVentaDet> remitoVentaDets = new HashSet<RemitoVentaDet>(0);
     private Set<BalanceIngreso> balanceIngresos = new HashSet<BalanceIngreso>(0);
     private Set<CategoriaDet> categoriaDets = new HashSet<CategoriaDet>(0);
     private Set<VentaDet> ventaDets = new HashSet<VentaDet>(0);
     private Set<CompraDet> compraDets = new HashSet<CompraDet>(0);
     private Set<MovStockDet> movStockDets = new HashSet<MovStockDet>(0);
     private Set<Categoria> categorias = new HashSet<Categoria>(0);
     private Set<BalanceInvIni> balanceInvInis = new HashSet<BalanceInvIni>(0);
     private Set<BalanceRemanente> balanceRemanentes = new HashSet<BalanceRemanente>(0);
     private Set<ListaPreciosDet> listaPreciosDets = new HashSet<ListaPreciosDet>(0);

    public Producto() {
    }

	
    public Producto(Rubro rubro, Unidad unidad, String nombre, String descripcion, char tipo, BigDecimal porcIva, char estado) {
        this.rubro = rubro;
        this.unidad = unidad;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tipo = tipo;
        this.porcIva = porcIva;
        this.estado = estado;
    }
    public Producto(Rubro rubro, Unidad unidad, String codigo, String nombre, String descripcion, char tipo, BigDecimal porcIva, BigDecimal stockMinimo, char estado, Set<RemitoVentaDet> remitoVentaDets, Set<BalanceIngreso> balanceIngresos, Set<CategoriaDet> categoriaDets, Set<VentaDet> ventaDets, Set<CompraDet> compraDets, Set<MovStockDet> movStockDets, Set<Categoria> categorias, Set<BalanceInvIni> balanceInvInis, Set<BalanceRemanente> balanceRemanentes, Set<ListaPreciosDet> listaPreciosDets) {
       this.rubro = rubro;
       this.unidad = unidad;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.porcIva = porcIva;
       this.stockMinimo = stockMinimo;
       this.estado = estado;
       this.remitoVentaDets = remitoVentaDets;
       this.balanceIngresos = balanceIngresos;
       this.categoriaDets = categoriaDets;
       this.ventaDets = ventaDets;
       this.compraDets = compraDets;
       this.movStockDets = movStockDets;
       this.categorias = categorias;
       this.balanceInvInis = balanceInvInis;
       this.balanceRemanentes = balanceRemanentes;
       this.listaPreciosDets = listaPreciosDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(BigDecimal stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<RemitoVentaDet> getRemitoVentaDets() {
        return this.remitoVentaDets;
    }
    
    public void setRemitoVentaDets(Set<RemitoVentaDet> remitoVentaDets) {
        this.remitoVentaDets = remitoVentaDets;
    }
    public Set<BalanceIngreso> getBalanceIngresos() {
        return this.balanceIngresos;
    }
    
    public void setBalanceIngresos(Set<BalanceIngreso> balanceIngresos) {
        this.balanceIngresos = balanceIngresos;
    }
    public Set<CategoriaDet> getCategoriaDets() {
        return this.categoriaDets;
    }
    
    public void setCategoriaDets(Set<CategoriaDet> categoriaDets) {
        this.categoriaDets = categoriaDets;
    }
    public Set<VentaDet> getVentaDets() {
        return this.ventaDets;
    }
    
    public void setVentaDets(Set<VentaDet> ventaDets) {
        this.ventaDets = ventaDets;
    }
    public Set<CompraDet> getCompraDets() {
        return this.compraDets;
    }
    
    public void setCompraDets(Set<CompraDet> compraDets) {
        this.compraDets = compraDets;
    }
    public Set<MovStockDet> getMovStockDets() {
        return this.movStockDets;
    }
    
    public void setMovStockDets(Set<MovStockDet> movStockDets) {
        this.movStockDets = movStockDets;
    }
    public Set<Categoria> getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set<Categoria> categorias) {
        this.categorias = categorias;
    }
    public Set<BalanceInvIni> getBalanceInvInis() {
        return this.balanceInvInis;
    }
    
    public void setBalanceInvInis(Set<BalanceInvIni> balanceInvInis) {
        this.balanceInvInis = balanceInvInis;
    }
    public Set<BalanceRemanente> getBalanceRemanentes() {
        return this.balanceRemanentes;
    }
    
    public void setBalanceRemanentes(Set<BalanceRemanente> balanceRemanentes) {
        this.balanceRemanentes = balanceRemanentes;
    }
    public Set<ListaPreciosDet> getListaPreciosDets() {
        return this.listaPreciosDets;
    }
    
    public void setListaPreciosDets(Set<ListaPreciosDet> listaPreciosDets) {
        this.listaPreciosDets = listaPreciosDets;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + Objects.hashCode(this.id);
        hash = 59 * hash + Objects.hashCode(this.rubro);
        hash = 59 * hash + Objects.hashCode(this.unidad);
        hash = 59 * hash + Objects.hashCode(this.codigo);
        hash = 59 * hash + Objects.hashCode(this.nombre);
        hash = 59 * hash + Objects.hashCode(this.descripcion);
        hash = 59 * hash + this.tipo;
        hash = 59 * hash + Objects.hashCode(this.porcIva);
        hash = 59 * hash + Objects.hashCode(this.stockMinimo);
        hash = 59 * hash + this.estado;
        hash = 59 * hash + Objects.hashCode(this.remitoVentaDets);
        hash = 59 * hash + Objects.hashCode(this.balanceIngresos);
        hash = 59 * hash + Objects.hashCode(this.categoriaDets);
        hash = 59 * hash + Objects.hashCode(this.ventaDets);
        hash = 59 * hash + Objects.hashCode(this.compraDets);
        hash = 59 * hash + Objects.hashCode(this.movStockDets);
        hash = 59 * hash + Objects.hashCode(this.categorias);
        hash = 59 * hash + Objects.hashCode(this.balanceInvInis);
        hash = 59 * hash + Objects.hashCode(this.balanceRemanentes);
        hash = 59 * hash + Objects.hashCode(this.listaPreciosDets);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Producto other = (Producto) obj;
        if (this.tipo != other.tipo) {
            return false;
        }
        if (this.estado != other.estado) {
            return false;
        }
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        if (!Objects.equals(this.nombre, other.nombre)) {
            return false;
        }
        if (!Objects.equals(this.descripcion, other.descripcion)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.rubro, other.rubro)) {
            return false;
        }
        if (!Objects.equals(this.unidad, other.unidad)) {
            return false;
        }
        if (!Objects.equals(this.porcIva, other.porcIva)) {
            return false;
        }
        if (!Objects.equals(this.stockMinimo, other.stockMinimo)) {
            return false;
        }
        if (!Objects.equals(this.remitoVentaDets, other.remitoVentaDets)) {
            return false;
        }
        if (!Objects.equals(this.balanceIngresos, other.balanceIngresos)) {
            return false;
        }
        if (!Objects.equals(this.categoriaDets, other.categoriaDets)) {
            return false;
        }
        if (!Objects.equals(this.ventaDets, other.ventaDets)) {
            return false;
        }
        if (!Objects.equals(this.compraDets, other.compraDets)) {
            return false;
        }
        if (!Objects.equals(this.movStockDets, other.movStockDets)) {
            return false;
        }
        if (!Objects.equals(this.categorias, other.categorias)) {
            return false;
        }
        if (!Objects.equals(this.balanceInvInis, other.balanceInvInis)) {
            return false;
        }
        if (!Objects.equals(this.balanceRemanentes, other.balanceRemanentes)) {
            return false;
        }
        if (!Objects.equals(this.listaPreciosDets, other.listaPreciosDets)) {
            return false;
        }
        return true;
    }




}


