package entidades;
// Generated 10/07/2021 10:15:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rubro generated by hbm2java
 */
public class Rubro  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<LocalRubro> localRubros = new HashSet<LocalRubro>(0);

    public Rubro() {
    }

	
    public Rubro(String nombre) {
        this.nombre = nombre;
    }
    public Rubro(String nombre, Set<Producto> productos) {
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

    public Set<LocalRubro> getLocalRubros() {
        return localRubros;
    }

    public void setLocalRubros(Set<LocalRubro> localRubros) {
        this.localRubros = localRubros;
    }

    




}


