package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private Short id;
     private Empresa empresa;
     private String nombre;
     private Set<MesaNumero> mesaNumeros = new HashSet<MesaNumero>(0);

    public Sector() {
    }

	
    public Sector(Empresa empresa, String nombre) {
        this.empresa = empresa;
        this.nombre = nombre;
    }
    public Sector(Empresa empresa, String nombre, Set<MesaNumero> mesaNumeros) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.mesaNumeros = mesaNumeros;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<MesaNumero> getMesaNumeros() {
        return this.mesaNumeros;
    }
    
    public void setMesaNumeros(Set<MesaNumero> mesaNumeros) {
        this.mesaNumeros = mesaNumeros;
    }




}


