package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private String nombre;
     private Set<VentaCuenta> ventaCuentas = new HashSet<VentaCuenta>(0);
     private Set<MesaComprobante> mesaComprobantes = new HashSet<MesaComprobante>(0);

    public Tarjeta() {
    }

	
    public Tarjeta(Empresa empresa, String nombre) {
        this.empresa = empresa;
        this.nombre = nombre;
    }
    public Tarjeta(Empresa empresa, String nombre, Set<VentaCuenta> ventaCuentas, Set<MesaComprobante> mesaComprobantes) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.ventaCuentas = ventaCuentas;
       this.mesaComprobantes = mesaComprobantes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<VentaCuenta> getVentaCuentas() {
        return this.ventaCuentas;
    }
    
    public void setVentaCuentas(Set<VentaCuenta> ventaCuentas) {
        this.ventaCuentas = ventaCuentas;
    }
    public Set<MesaComprobante> getMesaComprobantes() {
        return this.mesaComprobantes;
    }
    
    public void setMesaComprobantes(Set<MesaComprobante> mesaComprobantes) {
        this.mesaComprobantes = mesaComprobantes;
    }




}


