package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoFactura generated by hbm2java
 */
public class TipoFactura  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<MesaComprobante> mesaComprobantes = new HashSet<MesaComprobante>(0);

    public TipoFactura() {
    }

	
    public TipoFactura(String nombre) {
        this.nombre = nombre;
    }
    public TipoFactura(String nombre, Set<MesaComprobante> mesaComprobantes) {
       this.nombre = nombre;
       this.mesaComprobantes = mesaComprobantes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<MesaComprobante> getMesaComprobantes() {
        return this.mesaComprobantes;
    }
    
    public void setMesaComprobantes(Set<MesaComprobante> mesaComprobantes) {
        this.mesaComprobantes = mesaComprobantes;
    }




}


