package entidades;
// Generated 20/08/2020 18:04:52 by Hibernate Tools 4.3.1



/**
 * UnidadTransportada generated by hbm2java
 */
public class UnidadTransportada  implements java.io.Serializable {


     private Short id;
     private String nombre;

    public UnidadTransportada() {
    }

    public UnidadTransportada(String nombre) {
       this.nombre = nombre;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


