package entidades;
// Generated 16/12/2020 15:28:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioAdmin generated by hbm2java
 */
public class UsuarioAdmin  implements java.io.Serializable {


     private Integer id;
     private Area area= new Area();
     private Cargo cargo= new Cargo();
     private String nombreUsuario;
     private String clave;
     private String apellido;
     private String nombre;
     private Date fecha;
     private char tipo;
     private char estado;
     private Set<EfectivoFlete> efectivoFletes = new HashSet<EfectivoFlete>(0);
     private Set<Gasto> gastos = new HashSet<Gasto>(0);
     private Set<Tropa> tropas = new HashSet<Tropa>(0);
     private Set<MovInventario> movInventarios = new HashSet<MovInventario>(0);
     private Set<LiquidacionFlete> liquidacionFletes = new HashSet<LiquidacionFlete>(0);
     private Set<Fletero> fleteros = new HashSet<Fletero>(0);
     private Set<Entrega> entregasForIdUsuarioRecibe = new HashSet<Entrega>(0);
     private Set<Entrega> entregasForIdUsuarioEntrega = new HashSet<Entrega>(0);

    public UsuarioAdmin() {
    }

	
    public UsuarioAdmin(String nombreUsuario, String clave, String apellido, String nombre, Date fecha, char tipo, char estado) {
        this.nombreUsuario = nombreUsuario;
        this.clave = clave;
        this.apellido = apellido;
        this.nombre = nombre;
        this.fecha = fecha;
        this.tipo = tipo;
        this.estado = estado;
    }
    public UsuarioAdmin(Area area, Cargo cargo, String nombreUsuario, String clave, String apellido, String nombre, Date fecha, char tipo, char estado, Set<EfectivoFlete> efectivoFletes, Set<Gasto> gastos, Set<Tropa> tropas, Set<MovInventario> movInventarios, Set<LiquidacionFlete> liquidacionFletes, Set<Fletero> fleteros, Set<Entrega> entregasForIdUsuarioRecibe, Set<Entrega> entregasForIdUsuarioEntrega) {
       this.area = area;
       this.cargo = cargo;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fecha = fecha;
       this.tipo = tipo;
       this.estado = estado;
       this.efectivoFletes = efectivoFletes;
       this.gastos = gastos;
       this.tropas = tropas;
       this.movInventarios = movInventarios;
       this.liquidacionFletes = liquidacionFletes;
       this.fleteros = fleteros;
       this.entregasForIdUsuarioRecibe = entregasForIdUsuarioRecibe;
       this.entregasForIdUsuarioEntrega = entregasForIdUsuarioEntrega;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set<EfectivoFlete> getEfectivoFletes() {
        return this.efectivoFletes;
    }
    
    public void setEfectivoFletes(Set<EfectivoFlete> efectivoFletes) {
        this.efectivoFletes = efectivoFletes;
    }
    public Set<Gasto> getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set<Gasto> gastos) {
        this.gastos = gastos;
    }
    public Set<Tropa> getTropas() {
        return this.tropas;
    }
    
    public void setTropas(Set<Tropa> tropas) {
        this.tropas = tropas;
    }
    public Set<MovInventario> getMovInventarios() {
        return this.movInventarios;
    }
    
    public void setMovInventarios(Set<MovInventario> movInventarios) {
        this.movInventarios = movInventarios;
    }
    public Set<LiquidacionFlete> getLiquidacionFletes() {
        return this.liquidacionFletes;
    }
    
    public void setLiquidacionFletes(Set<LiquidacionFlete> liquidacionFletes) {
        this.liquidacionFletes = liquidacionFletes;
    }
    public Set<Fletero> getFleteros() {
        return this.fleteros;
    }
    
    public void setFleteros(Set<Fletero> fleteros) {
        this.fleteros = fleteros;
    }
    public Set<Entrega> getEntregasForIdUsuarioRecibe() {
        return this.entregasForIdUsuarioRecibe;
    }
    
    public void setEntregasForIdUsuarioRecibe(Set<Entrega> entregasForIdUsuarioRecibe) {
        this.entregasForIdUsuarioRecibe = entregasForIdUsuarioRecibe;
    }
    public Set<Entrega> getEntregasForIdUsuarioEntrega() {
        return this.entregasForIdUsuarioEntrega;
    }
    
    public void setEntregasForIdUsuarioEntrega(Set<Entrega> entregasForIdUsuarioEntrega) {
        this.entregasForIdUsuarioEntrega = entregasForIdUsuarioEntrega;
    }




}


