package entidades;
// Generated 24 ago. 2021 15:17:14 by Hibernate Tools 4.3.1



/**
 * VentaRemito generated by hbm2java
 */
public class VentaRemito  implements java.io.Serializable {


     private Integer id;
     private RemitoVenta remitoVenta;
     private Venta venta;

    public VentaRemito() {
    }

    public VentaRemito(RemitoVenta remitoVenta, Venta venta) {
       this.remitoVenta = remitoVenta;
       this.venta = venta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RemitoVenta getRemitoVenta() {
        return this.remitoVenta;
    }
    
    public void setRemitoVenta(RemitoVenta remitoVenta) {
        this.remitoVenta = remitoVenta;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


