package entidades;
// Generated 16 jun. 2022 20:10:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VentaDet generated by hbm2java
 */
public class VentaDet  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private Tropa tropa;
     private Unidad unidad;
     private Venta venta;
     private BigDecimal precio;
     private BigDecimal porcDesc;
     private BigDecimal valorDesc;
     private BigDecimal precioFinal;
     private BigDecimal cantidad;
     private BigDecimal valorFinal;

    public VentaDet() {
    }

	
    public VentaDet(Producto producto, Unidad unidad, Venta venta, BigDecimal precio, BigDecimal porcDesc, BigDecimal valorDesc, BigDecimal precioFinal, BigDecimal cantidad, BigDecimal valorFinal) {
        this.producto = producto;
        this.unidad = unidad;
        this.venta = venta;
        this.precio = precio;
        this.porcDesc = porcDesc;
        this.valorDesc = valorDesc;
        this.precioFinal = precioFinal;
        this.cantidad = cantidad;
        this.valorFinal = valorFinal;
    }
    public VentaDet(Producto producto, Tropa tropa, Unidad unidad, Venta venta, BigDecimal precio, BigDecimal porcDesc, BigDecimal valorDesc, BigDecimal precioFinal, BigDecimal cantidad, BigDecimal valorFinal) {
       this.producto = producto;
       this.tropa = tropa;
       this.unidad = unidad;
       this.venta = venta;
       this.precio = precio;
       this.porcDesc = porcDesc;
       this.valorDesc = valorDesc;
       this.precioFinal = precioFinal;
       this.cantidad = cantidad;
       this.valorFinal = valorFinal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tropa getTropa() {
        return this.tropa;
    }
    
    public void setTropa(Tropa tropa) {
        this.tropa = tropa;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getPorcDesc() {
        return this.porcDesc;
    }
    
    public void setPorcDesc(BigDecimal porcDesc) {
        this.porcDesc = porcDesc;
    }
    public BigDecimal getValorDesc() {
        return this.valorDesc;
    }
    
    public void setValorDesc(BigDecimal valorDesc) {
        this.valorDesc = valorDesc;
    }
    public BigDecimal getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(BigDecimal precioFinal) {
        this.precioFinal = precioFinal;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }




}


