package entidades;
// Generated 31 oct. 2021 16:10:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VentaCuenta generated by hbm2java
 */
public class VentaCuenta  implements java.io.Serializable {


     private int id;
     private FormaPago formaPago;
     private Tarjeta tarjeta;
     private Venta venta;
     private String numTarjeta;
     private Date fecVenc;
     private Date fecPago;
     private BigDecimal valor;

    public VentaCuenta() {
    }

	
    public VentaCuenta(int id, FormaPago formaPago, Venta venta, Date fecVenc, BigDecimal valor) {
        this.id = id;
        this.formaPago = formaPago;
        this.venta = venta;
        this.fecVenc = fecVenc;
        this.valor = valor;
    }
    public VentaCuenta(int id, FormaPago formaPago, Tarjeta tarjeta, Venta venta, String numTarjeta, Date fecVenc, Date fecPago, BigDecimal valor) {
       this.id = id;
       this.formaPago = formaPago;
       this.tarjeta = tarjeta;
       this.venta = venta;
       this.numTarjeta = numTarjeta;
       this.fecVenc = fecVenc;
       this.fecPago = fecPago;
       this.valor = valor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public String getNumTarjeta() {
        return this.numTarjeta;
    }
    
    public void setNumTarjeta(String numTarjeta) {
        this.numTarjeta = numTarjeta;
    }
    public Date getFecVenc() {
        return this.fecVenc;
    }
    
    public void setFecVenc(Date fecVenc) {
        this.fecVenc = fecVenc;
    }
    public Date getFecPago() {
        return this.fecPago;
    }
    
    public void setFecPago(Date fecPago) {
        this.fecPago = fecPago;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


